name: nit_app
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  serverpod_client: 2.1.5
  serverpod_auth_client: 2.1.5
  serverpod_auth_shared_flutter: 2.1.5
  serverpod_auth_phone_flutter:
    # path: ../nit_serverpod/modules/serverpod_auth/serverpod_auth_phone_flutter
    git:
        url: git@github.com:novikov-it/nit_serverpod.git
        path: modules/serverpod_auth/serverpod_auth_phone_flutter

  nit_tools_client:
    # path: ../nit_tools/nit_tools_client
    git:
      url: git@github.com:novikov-it/nit_tools.git
      path: nit_tools_client
      ref: chat

  nit_ui_kit: ^0.1.1
    # path: ../nit_ui_kit
    # git:
    #   url: git@github.com:novikov-it/nit_ui_kit.git
    #   ref: master

  nit_riverpod_notifications: ^0.0.1
  #   # path: ../nit_riverpod_notifications
  #   git:
  #     url: git@github.com:novikov-it/nit_riverpod_notifications.git
  #     ref: master

  nit_generic_forms: ^0.0.1
    # path: ../nit_generic_forms
    # git:
    #   url: git@github.com:novikov-it/nit_generic_forms.git
    
  scrollview_observer: ^1.26.1
    #   ref: master

  # chatview: # ^2.2.0
  #   # path: ../nit_flutter_chatview
  #   git:
  #     url: git@github.com:novikov-it/nit_flutter_chatview.git
  #     ref: main

  intl: ^0.19.0
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.10
  go_router: ^10.1.2
  oktoast: ^3.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.3
  collection: ^1.18.0

  app_links: ^6.3.2
  flutter_multi_formatter: ^2.13.0
  heif_converter: ^1.0.1
  image: ^4.5.4
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2

  #chat
  visibility_detector: ^0.4.0
  wechat_assets_picker: ^9.5.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  http: ^1.4.0
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11

dependency_overrides:

  # serverpod_chat_client:
  #   # path: ../nit_serverpod/modules/serverpod_chat/serverpod_chat_client
  #   git:
  #       url: git@github.com:novikov-it/nit_serverpod.git
  #       path: modules/serverpod_chat/serverpod_chat_client
  #       ref: main
  # serverpod_chat_flutter:
  #   # path: ../nit_serverpod/modules/serverpod_chat/serverpod_chat_flutter
  #   git:
  #       url: git@github.com:novikov-it/nit_serverpod.git
  #       path: modules/serverpod_chat/serverpod_chat_flutter
  #       ref: main
  serverpod_auth_client:
    # path: ../nit_serverpod/modules/serverpod_auth/serverpod_auth_client
    git:
      url: git@github.com:novikov-it/nit_serverpod.git
      path: modules/serverpod_auth/serverpod_auth_client

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
